# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/connor/Documents/Repos/pocket-term

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/connor/Documents/Repos/pocket-term

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/connor/Documents/Repos/pocket-term/CMakeFiles /Users/connor/Documents/Repos/pocket-term//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/connor/Documents/Repos/pocket-term/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pocket-term

# Build rule for target.
pocket-term: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pocket-term
.PHONY : pocket-term

# fast build rule for target.
pocket-term/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/build
.PHONY : pocket-term/fast

app_manager.o: app_manager.cpp.o
.PHONY : app_manager.o

# target to build an object file
app_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/app_manager.cpp.o
.PHONY : app_manager.cpp.o

app_manager.i: app_manager.cpp.i
.PHONY : app_manager.i

# target to preprocess a source file
app_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/app_manager.cpp.i
.PHONY : app_manager.cpp.i

app_manager.s: app_manager.cpp.s
.PHONY : app_manager.s

# target to generate assembly for a file
app_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/app_manager.cpp.s
.PHONY : app_manager.cpp.s

apps/app.o: apps/app.cpp.o
.PHONY : apps/app.o

# target to build an object file
apps/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/app.cpp.o
.PHONY : apps/app.cpp.o

apps/app.i: apps/app.cpp.i
.PHONY : apps/app.i

# target to preprocess a source file
apps/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/app.cpp.i
.PHONY : apps/app.cpp.i

apps/app.s: apps/app.cpp.s
.PHONY : apps/app.s

# target to generate assembly for a file
apps/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/app.cpp.s
.PHONY : apps/app.cpp.s

apps/home.o: apps/home.cpp.o
.PHONY : apps/home.o

# target to build an object file
apps/home.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/home.cpp.o
.PHONY : apps/home.cpp.o

apps/home.i: apps/home.cpp.i
.PHONY : apps/home.i

# target to preprocess a source file
apps/home.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/home.cpp.i
.PHONY : apps/home.cpp.i

apps/home.s: apps/home.cpp.s
.PHONY : apps/home.s

# target to generate assembly for a file
apps/home.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/home.cpp.s
.PHONY : apps/home.cpp.s

apps/launcher.o: apps/launcher.cpp.o
.PHONY : apps/launcher.o

# target to build an object file
apps/launcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/launcher.cpp.o
.PHONY : apps/launcher.cpp.o

apps/launcher.i: apps/launcher.cpp.i
.PHONY : apps/launcher.i

# target to preprocess a source file
apps/launcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/launcher.cpp.i
.PHONY : apps/launcher.cpp.i

apps/launcher.s: apps/launcher.cpp.s
.PHONY : apps/launcher.s

# target to generate assembly for a file
apps/launcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/apps/launcher.cpp.s
.PHONY : apps/launcher.cpp.s

drivers/cardkb.o: drivers/cardkb.cpp.o
.PHONY : drivers/cardkb.o

# target to build an object file
drivers/cardkb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/cardkb.cpp.o
.PHONY : drivers/cardkb.cpp.o

drivers/cardkb.i: drivers/cardkb.cpp.i
.PHONY : drivers/cardkb.i

# target to preprocess a source file
drivers/cardkb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/cardkb.cpp.i
.PHONY : drivers/cardkb.cpp.i

drivers/cardkb.s: drivers/cardkb.cpp.s
.PHONY : drivers/cardkb.s

# target to generate assembly for a file
drivers/cardkb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/cardkb.cpp.s
.PHONY : drivers/cardkb.cpp.s

drivers/display.o: drivers/display.cpp.o
.PHONY : drivers/display.o

# target to build an object file
drivers/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/display.cpp.o
.PHONY : drivers/display.cpp.o

drivers/display.i: drivers/display.cpp.i
.PHONY : drivers/display.i

# target to preprocess a source file
drivers/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/display.cpp.i
.PHONY : drivers/display.cpp.i

drivers/display.s: drivers/display.cpp.s
.PHONY : drivers/display.s

# target to generate assembly for a file
drivers/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/display.cpp.s
.PHONY : drivers/display.cpp.s

drivers/event_source.o: drivers/event_source.cpp.o
.PHONY : drivers/event_source.o

# target to build an object file
drivers/event_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/event_source.cpp.o
.PHONY : drivers/event_source.cpp.o

drivers/event_source.i: drivers/event_source.cpp.i
.PHONY : drivers/event_source.i

# target to preprocess a source file
drivers/event_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/event_source.cpp.i
.PHONY : drivers/event_source.cpp.i

drivers/event_source.s: drivers/event_source.cpp.s
.PHONY : drivers/event_source.s

# target to generate assembly for a file
drivers/event_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/event_source.cpp.s
.PHONY : drivers/event_source.cpp.s

drivers/sim800l.o: drivers/sim800l.cpp.o
.PHONY : drivers/sim800l.o

# target to build an object file
drivers/sim800l.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/sim800l.cpp.o
.PHONY : drivers/sim800l.cpp.o

drivers/sim800l.i: drivers/sim800l.cpp.i
.PHONY : drivers/sim800l.i

# target to preprocess a source file
drivers/sim800l.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/sim800l.cpp.i
.PHONY : drivers/sim800l.cpp.i

drivers/sim800l.s: drivers/sim800l.cpp.s
.PHONY : drivers/sim800l.s

# target to generate assembly for a file
drivers/sim800l.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/sim800l.cpp.s
.PHONY : drivers/sim800l.cpp.s

drivers/tty_display.o: drivers/tty_display.cpp.o
.PHONY : drivers/tty_display.o

# target to build an object file
drivers/tty_display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/tty_display.cpp.o
.PHONY : drivers/tty_display.cpp.o

drivers/tty_display.i: drivers/tty_display.cpp.i
.PHONY : drivers/tty_display.i

# target to preprocess a source file
drivers/tty_display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/tty_display.cpp.i
.PHONY : drivers/tty_display.cpp.i

drivers/tty_display.s: drivers/tty_display.cpp.s
.PHONY : drivers/tty_display.s

# target to generate assembly for a file
drivers/tty_display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/drivers/tty_display.cpp.s
.PHONY : drivers/tty_display.cpp.s

event.o: event.cpp.o
.PHONY : event.o

# target to build an object file
event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/event.cpp.o
.PHONY : event.cpp.o

event.i: event.cpp.i
.PHONY : event.i

# target to preprocess a source file
event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/event.cpp.i
.PHONY : event.cpp.i

event.s: event.cpp.s
.PHONY : event.s

# target to generate assembly for a file
event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/event.cpp.s
.PHONY : event.cpp.s

logging.o: logging.cpp.o
.PHONY : logging.o

# target to build an object file
logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/logging.cpp.o
.PHONY : logging.cpp.o

logging.i: logging.cpp.i
.PHONY : logging.i

# target to preprocess a source file
logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/logging.cpp.i
.PHONY : logging.cpp.i

logging.s: logging.cpp.s
.PHONY : logging.s

# target to generate assembly for a file
logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/logging.cpp.s
.PHONY : logging.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/main.cpp.s
.PHONY : main.cpp.s

os.o: os.cpp.o
.PHONY : os.o

# target to build an object file
os.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/os.cpp.o
.PHONY : os.cpp.o

os.i: os.cpp.i
.PHONY : os.i

# target to preprocess a source file
os.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/os.cpp.i
.PHONY : os.cpp.i

os.s: os.cpp.s
.PHONY : os.s

# target to generate assembly for a file
os.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/os.cpp.s
.PHONY : os.cpp.s

ui/screen.o: ui/screen.cpp.o
.PHONY : ui/screen.o

# target to build an object file
ui/screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/screen.cpp.o
.PHONY : ui/screen.cpp.o

ui/screen.i: ui/screen.cpp.i
.PHONY : ui/screen.i

# target to preprocess a source file
ui/screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/screen.cpp.i
.PHONY : ui/screen.cpp.i

ui/screen.s: ui/screen.cpp.s
.PHONY : ui/screen.s

# target to generate assembly for a file
ui/screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/screen.cpp.s
.PHONY : ui/screen.cpp.s

ui/ui.o: ui/ui.cpp.o
.PHONY : ui/ui.o

# target to build an object file
ui/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/ui.cpp.o
.PHONY : ui/ui.cpp.o

ui/ui.i: ui/ui.cpp.i
.PHONY : ui/ui.i

# target to preprocess a source file
ui/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/ui.cpp.i
.PHONY : ui/ui.cpp.i

ui/ui.s: ui/ui.cpp.s
.PHONY : ui/ui.s

# target to generate assembly for a file
ui/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/ui/ui.cpp.s
.PHONY : ui/ui.cpp.s

utilities.o: utilities.cpp.o
.PHONY : utilities.o

# target to build an object file
utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/utilities.cpp.o
.PHONY : utilities.cpp.o

utilities.i: utilities.cpp.i
.PHONY : utilities.i

# target to preprocess a source file
utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/utilities.cpp.i
.PHONY : utilities.cpp.i

utilities.s: utilities.cpp.s
.PHONY : utilities.s

# target to generate assembly for a file
utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pocket-term.dir/build.make CMakeFiles/pocket-term.dir/utilities.cpp.s
.PHONY : utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... pocket-term"
	@echo "... app_manager.o"
	@echo "... app_manager.i"
	@echo "... app_manager.s"
	@echo "... apps/app.o"
	@echo "... apps/app.i"
	@echo "... apps/app.s"
	@echo "... apps/home.o"
	@echo "... apps/home.i"
	@echo "... apps/home.s"
	@echo "... apps/launcher.o"
	@echo "... apps/launcher.i"
	@echo "... apps/launcher.s"
	@echo "... drivers/cardkb.o"
	@echo "... drivers/cardkb.i"
	@echo "... drivers/cardkb.s"
	@echo "... drivers/display.o"
	@echo "... drivers/display.i"
	@echo "... drivers/display.s"
	@echo "... drivers/event_source.o"
	@echo "... drivers/event_source.i"
	@echo "... drivers/event_source.s"
	@echo "... drivers/sim800l.o"
	@echo "... drivers/sim800l.i"
	@echo "... drivers/sim800l.s"
	@echo "... drivers/tty_display.o"
	@echo "... drivers/tty_display.i"
	@echo "... drivers/tty_display.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... logging.o"
	@echo "... logging.i"
	@echo "... logging.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... os.o"
	@echo "... os.i"
	@echo "... os.s"
	@echo "... ui/screen.o"
	@echo "... ui/screen.i"
	@echo "... ui/screen.s"
	@echo "... ui/ui.o"
	@echo "... ui/ui.i"
	@echo "... ui/ui.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

